""" Constants file for Auth0's seed project
"""
ACCESS_TOKEN_KEY = 'access_token'
API_ID = 'API_ID'
APP_JSON_KEY = 'application/json'
AUTH0_CLIENT_ID = 'AUTH0_CLIENT_ID'
AUTH0_CLIENT_SECRET = 'AUTH0_CLIENT_SECRET'
AUTH0_CALLBACK_URL = 'AUTH0_CALLBACK_URL'
AUTH0_DOMAIN = 'AUTH0_DOMAIN'
AUTH0_AUDIENCE = 'AUTH0_AUDIENCE'
AUTHORIZATION_CODE_KEY = 'authorization_code'
CLIENT_ID_KEY = 'client_id'
CLIENT_SECRET_KEY = 'client_secret'
CODE_KEY = 'code'
CONTENT_TYPE_KEY = 'content-type'
GRANT_TYPE_KEY = 'grant_type'
PROFILE_KEY = 'profile'
REDIRECT_URI_KEY = 'redirect_uri'
SECRET_KEY = 'ThisIsTheSecretKey'
JWT_PAYLOAD = 'jwt_payload'
MYSQL_DATABASE_HOST = 'MYSQL_DATABASE_HOST'
MYSQL_DATABASE_PORT = 'MYSQL_DATABASE_PORT'
MYSQL_DATABASE_USER = 'MYSQL_DATABASE_USER'
MYSQL_DATABASE_PASSWORD = 'MYSQL_DATABASE_PASSWORD'
MYSQL_DATABASE_DB = 'MYSQL_DATABASE_DB'
MYSQL_DATABASE_SOCKET = 'MYSQL_DATABASE_SOCKET'
MYSQL_UNIX_SOCKET = 'MYSQL_UNIX_SOCKET'
MYSQL_DATABASE_CHARSET = 'MYSQL_DATABASE_CHARSET'
SERVER_PORT = 'SERVER_PORT'
TIME_DELAY = 60

""" Bitcoin Server Info"""
ACCOUNT_ID = 16
PURPOSE = 44
BITCOIN_NETWORK = 'testnet'
WALLET_NAME = 'MarketExchange'

WEB_START_URL = '/Volumes/WORK/Progress/MarketExchange/front-end/'
"""
WEB_START_URL = '/home/ubuntu/marketexchange/front-end/'
"""